name: Lembrete de reunião

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  lembrete_reuniao:
    name: Lembrete de reunião
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python src/automations/lembrete-reuniao.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
